---
title: "Map & Analysis of Pedestrian & Bike Injuries in San Antonio, TX"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      echo = FALSE)

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
options(tigris_use_cache = TRUE)

# Parameters
pedestrian_injury_lines_url <- "https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/pwSeverePedestrianInjuryAreas/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
bike_facilities_lines_url <- "https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/Bike_Facilities/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
sidewalk_inventory_url <- "https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/Sidewalks/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
street_inventory_url <- "https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/Streets/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
bike_injury_lines_url <- "https://services.arcgis.com/g1fRTDLeMgspWrYp/arcgis/rest/services/pwSevereBicyclistInjuryAreas/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"

```


# Data Import
```{r}

# Ped & Biking Data
ped_injuries <- st_read(pedestrian_injury_lines_url)
bike_injuries <- st_read(bike_injury_lines_url)
sidewalks <- st_read(sidewalk_inventory_url)
bike_facilities <- st_read(bike_facilities_lines_url)
streets <- st_read(street_inventory_url)


# Census & Population Demographics

pop_estimates <- get_estimates(geography = "county",
                               year = 2022,
                               geometry = TRUE,
                               resolution = "20m"
                               )

places_sf <- places(state = "48", year =2022)
```

# Maps
```{r}


```

# Analysis
```{r}

```


## Exports
```{r}

```

