---
title: "Population Statistics Data Extraction"
author: "Francine Stephens"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE, 
                      message = FALSE,
                      echo = FALSE)

library(tidyverse)
library(tidycensus)
library(tigris)
library(sf)
options(tigris_use_cache = TRUE)

# Parameters


```

```{r}

bank_locations <- st_read(
  "https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/FDIC_InsuredBanks/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson")
```

# Data Import
```{r}
# Population

## 2022
pop_estimates <- get_estimates(geography = "county",
                               year = 2022,
                               geometry = TRUE,
                               resolution = "20m"
                               )


## 2017
pop_estimates17 <- get_estimates(geography = "county",
                               year = 2017,
                               variables = c("POP" 
                                             # "BIRTHS", 
                                             # "DEATHS", 
                                             # "RNATURALINC"
                                             ),
                               geometry = TRUE,
                               resolution = "20m"
                               )
```

```{r}
# Migration Flows
tx_flows <- get_flows(
  geography = "county",
  state = "TX",
  year = 2020,
  geometry = TRUE
  )
```


```{r}
# Places
places_sf <- places(state = "48", year =2022)

county_seats <- places_sf %>% 
  filter(NAME %in% county_table$county_seats) %>% 
  mutate(geometry = st_centroid(geometry)) 

```


## Export Data
```{r}
write_rds(pop_estimates, paste0(data_folder,
                                "population_estimates_2022.rds"))
write_rds(pop_estimates17, paste0(data_folder, 
                                  "population_estimates_2017.rds"))

write_rds(tx_flows, paste0(data_folder, 
                                  "migration_flows_2022_sf.rds"))


write_rds(county_seats, paste0(data_folder, 
                               "county_seats_sf.rds"))
```

